name = "Exodus"
uuid = "f57ae99e-f805-4780-bdca-96e224be1e5a"
version = "0.14.4"
authors = ["cmhamel <cmhamel32@gmail.com>"]

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Exodus_jll = "fc7263ad-bce8-5229-97b1-c6ddabda41b1"

[weakdeps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
ExodusMeshesExt = "Meshes"
ExodusUnitfulExt = "Unitful"

[compat]
Aqua = "0.8"
CEnum = "0.5.0"
DocStringExtensions = "0.9"
Exodus_jll = "9"
Meshes = "0.53"
Test = "1"
Unitful = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "Meshes", "Test", "Unitful"]
