name: CI

on: 
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: 
          - 'nightly'
          - '1.9'
          - '1.8'
        julia-arch: 
          - x64
        os:
          - macos-latest
          - ubuntu-latest 
          - windows-latest
        exclude:
          - os: windows-latest
            julia-version: 'nightly'
        
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
        # new stuff
        #
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      # - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-runtest@v1
      - run: |
          julia -e '
            using Pkg
            pkg"activate ."
            pkg"dev https://github.com/cmhamel/Exodus_jll.git"
            pkg"test"
          '
        with:
          annotate: true
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
          fail_ci_if_error: false
          verbose: true

  # test-ignore-hashes:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       julia-version: 
  #         - '1.9'
  #         - '1.8'
  #         - 'nightly'
  #       julia-arch: 
  #         - x64
  #       os:
  #         - macos-latest
  #         # - windows-latest
        
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@v1
  #       with:
  #         version: ${{ matrix.julia-version }}
  #         arch: ${{ matrix.julia-arch }}
  #       # new stuff
  #       #
  #     - uses: actions/cache@v1
  #       env:
  #         cache-name: cache-artifacts
  #       with:
  #         path: ~/.julia/artifacts
  #         key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-test-${{ env.cache-name }}-
  #           ${{ runner.os }}-test-
  #           ${{ runner.os }}-
  #     - run: |
  #         julia --color=yes -e '
  #           ENV["JULIA_PKG_IGNORE_HASHES"] = 1
  #           using Pkg
  #           Pkg.add("Exodus")
  #         '
  #     - uses: julia-actions/julia-runtest@v1
  #       with:
  #         annotate: true
  #     - uses: julia-actions/julia-processcoverage@v1
  #     - uses: codecov/codecov-action@v3
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         file: lcov.info
  #         fail_ci_if_error: false
  #         verbose: true
